/** @type {import('tailwindcss').Config} */
const colors = require("tailwindcss/colors");

module.exports = {
  darkMode: ["class"],
  content: [
    "./src/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./dist/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        ...colors,
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
      boxShadow: {
        DEFAULT:
          "0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)",
        sm: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        md: "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)",
        lg: "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
        xl: "0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)",
        "2xl": "0 25px 50px -12px rgb(0 0 0 / 0.25)",
        inner: "inset 0 2px 4px 0 rgb(0 0 0 / 0.05)",
        custom: "0 1px 1px rgba(0,0,0,0.1)",
        light: "0 1px 1px rgba(0,0,0,0.1)",
        none: "none",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
  safelist: [
    // Layout
    "rounded-md",
    "border",
    "h-10",
    "px-3",
    "py-2",
    "flex",
    "min-h-[80px]",
    "w-full",
    "items-center",
    "justify-between",
    "font-medium",
    "leading-none",
    "text-sm",

    // Height utilities
    "h-0",
    "h-px",
    "h-0.5",
    "h-1",
    "h-1.5",
    "h-2",
    "h-2.5",
    "h-3",
    "h-3.5",
    "h-4",
    "h-5",
    "h-6",
    "h-7",
    "h-8",
    "h-9",
    "h-10",
    "h-11",
    "h-12",
    "h-14",
    "h-16",
    "h-20",
    "h-24",
    "h-28",
    "h-32",
    "h-36",
    "h-40",
    "h-44",
    "h-48",
    "h-52",
    "h-56",
    "h-60",
    "h-64",
    "h-72",
    "h-80",
    "h-96",
    "h-auto",
    "h-full",
    "h-screen",
    "h-[1px]",

    // Width utilities
    "w-0",
    "w-px",
    "w-0.5",
    "w-1",
    "w-1.5",
    "w-2",
    "w-2.5",
    "w-3",
    "w-3.5",
    "w-4",
    "w-5",
    "w-6",
    "w-7",
    "w-8",
    "w-9",
    "w-10",
    "w-11",
    "w-12",
    "w-14",
    "w-16",
    "w-20",
    "w-24",
    "w-28",
    "w-32",
    "w-36",
    "w-40",
    "w-44",
    "w-48",
    "w-52",
    "w-56",
    "w-60",
    "w-64",
    "w-72",
    "w-80",
    "w-96",
    "w-auto",
    "w-full",
    "w-screen",
    "w-[1px]",

    // Margins and Padding
    {
      pattern: /^-?(m|p)[trblxy]?-[0-9]+$/,
    },
    // Padding utilities
    "p-1",
    "p-2",
    "p-3",
    "p-4",
    "pt-1",
    "pt-2",
    "pt-3",
    "pt-4",
    "pb-1",
    "pb-2",
    "pb-3",
    "pb-4",
    "pl-1",
    "pl-2",
    "pl-3",
    "pl-4",
    "pr-1",
    "pr-2",
    "pr-3",
    "pr-4",
    "px-1",
    "px-2",
    "px-3",
    "px-4",
    "py-1",
    "py-2",
    "py-3",
    "py-4",
    // Margin utilities
    "mt-1",
    "mt-2",
    "mt-3",
    "mt-4",
    "-mt-1",
    "-mt-2",
    "-mt-3",
    "-mt-4",
    "mb-1",
    "mb-2",
    "mb-3",
    "mb-4",
    "-mb-1",
    "-mb-2",
    "-mb-3",
    "-mb-4",
    "ml-1",
    "ml-2",
    "ml-3",
    "ml-4",
    "-ml-1",
    "-ml-2",
    "-ml-3",
    "-ml-4",
    "mr-1",
    "mr-2",
    "mr-3",
    "mr-4",
    "-mr-1",
    "-mr-2",
    "-mr-3",
    "-mr-4",

    // Sizes
    "h-4",
    "w-4",
    "shrink-0",

    // Borders and Shadows
    "rounded-sm",
    "border-primary",
    "shadow",
    "shadow-sm",
    "shadow-md",
    "shadow-lg",
    "shadow-xl",
    "shadow-2xl",
    "shadow-inner",
    "shadow-none",
    "shadow-[0_1px_1px_rgba(0,0,0,0.1)]",
    "shadow-custom",

    // Cursors
    "cursor-pointer",
    "cursor-default",
    "cursor-not-allowed",

    // Peer
    "peer",
    "peer-disabled:cursor-not-allowed",
    "peer-disabled:opacity-70",

    // Focus
    "focus-visible:outline-none",
    "focus-visible:ring-1",
    "focus-visible:ring-2",
    "focus-visible:ring-ring",
    "focus-visible:ring-offset-2",

    // States
    "disabled:cursor-not-allowed",
    "disabled:opacity-50",
    "data-[state=checked]:bg-primary",
    "data-[state=checked]:text-primary-foreground",

    // Colors
    "border-border",
    "border-input",
    "bg-background",
    "bg-primary",
    "bg-secondary",
    "bg-muted",
    "bg-accent",
    "bg-popover",
    "bg-card",
    "text-foreground",
    "text-primary",
    "text-primary-foreground",
    "text-secondary",
    "text-secondary-foreground",
    "text-muted",
    "text-muted-foreground",
    "text-accent",
    "text-accent-foreground",
    "text-destructive",
    "text-destructive-foreground",
    "ring-offset-background",

    // Default Tailwind Colors (common ones)
    {
      pattern:
        /^(bg|text|border)-(slate|gray|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-(50|100|200|300|400|500|600|700|800|900|950)(\/[0-9]+)?$/,
    },

    // Hover states for default colors
    "hover:bg-slate-100",
    "hover:bg-slate-200",
    "hover:bg-slate-300",
    "hover:bg-slate-400",
    "hover:bg-slate-500",
    "hover:bg-red-100",
    "hover:bg-red-200",
    "hover:bg-red-300",
    "hover:bg-red-400",
    "hover:bg-red-500",
    "hover:bg-blue-100",
    "hover:bg-blue-200",
    "hover:bg-blue-300",
    "hover:bg-blue-400",
    "hover:bg-blue-500",
    "hover:bg-green-100",
    "hover:bg-green-200",
    "hover:bg-green-300",
    "hover:bg-green-400",
    "hover:bg-green-500",

    // Hover states with opacity
    "hover:bg-slate-100/10",
    "hover:bg-slate-200/20",
    "hover:bg-slate-300/30",
    "hover:bg-slate-400/40",
    "hover:bg-slate-500/50",
    "hover:bg-red-100/10",
    "hover:bg-red-200/20",
    "hover:bg-red-300/30",
    "hover:bg-red-400/40",
    "hover:bg-red-500/50",

    // Hover states for theme colors
    "hover:bg-primary",
    "hover:bg-secondary",
    "hover:bg-muted",
    "hover:bg-accent",
    "hover:bg-background",
    "hover:bg-foreground",
    "hover:bg-card",
    "hover:bg-popover",
    "hover:bg-border",
    "hover:bg-input",
    "hover:bg-ring",
    "hover:bg-primary/90",
    "hover:bg-secondary/80",
    "hover:bg-muted/50",
    "hover:bg-accent/80",

    // Dark mode
    "dark:bg-background",
    "dark:text-foreground",
    "dark:border-border",
    "dark:hover:bg-primary/80",
    "dark:hover:bg-secondary/80",

    // Shadows
    "shadow",
    "shadow-sm",
    "shadow-md",
    "shadow-lg",
    "shadow-xl",
    "shadow-2xl",
    "shadow-inner",
    "shadow-none",
    "shadow-custom",
    {
      pattern: /^shadow-\[.+\]$/,
    },
    {
      pattern: /^box-shadow-\[.+\]$/,
    },
    {
      pattern: /^\[box-shadow:.+\]$/,
    },
    "[box-shadow:0_1px_1px_rgba(0,0,0,0.1)]",

    // Shadows
    "shadow",
    "shadow-sm",
    "shadow-md",
    "shadow-lg",
    "shadow-xl",
    "shadow-2xl",
    "shadow-inner",
    "shadow-none",
    "shadow-custom",
    "shadow-light",
  ],
};
